# -*- coding: utf-8 -*-
"""Image Editor

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iiaO1jXU-7oHfmJJ8eV4q6qKbkqpgNQi
"""

!wget https://images-assets.nasa.gov/image/as11-40-5874/as11-40-5874~thumb.jpg # sample url to link

from PIL import Image, ImageFilter, ImageEnhance
filename = "as11-40-5874~thumb.jpg" # replace with file name
with Image.open(filename) as img:
	img.load()

new_img = img

userInputRotate = input("How much degrees do you want to rotate the image: ")
new_img = new_img.rotate(int(userInputRotate))

userInputBlur = input("Would you like to blur the image? (y/n): ")
if userInputBlur == "y":
	new_img = new_img.filter(ImageFilter.BLUR)

userInputSharpen = input("Would you like to sharpen the image? (y/n): ")
if userInputSharpen == "y":
	new_img = new_img.filter(ImageFilter.SHARPEN)
 
userInputGrayFilter = input("Would you like to add a gray filter? (y/n): ")
if userInputGrayFilter == "y":
	new_img = new_img.convert("L")

userInputDisplayEdges = input("Would you like to display the edges? (y/n): ")
if userInputDisplayEdges == "y":
	new_img = new_img.convert("L")
	new_img = new_img.filter(ImageFilter.SMOOTH)
	new_img = new_img.filter(ImageFilter.FIND_EDGES)
 
userInputBrightness = input("Would you like to change the brightness? (0-2, 1 being original): ")
new_img = ImageEnhance.Brightness(new_img).enhance(float(userInputBrightness))

userInputContrast = input("Would you like to change the contrast? (0-2, 1 being original): ")
new_img = ImageEnhance.Contrast(new_img).enhance(float(userInputContrast))

print()
print("Original Image: ")
display(img)
print()
print("Modified Image: ")
display(new_img)